name: Publish

on:
  release:
    types: [ published ]

defaults:
  run:
    shell: bash -l {0}

jobs:
  Deploy:
    name: Deploy
    runs-on: macos-11
    environment: Publishing
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main

    - name: Install cocoapods
      run: gem install cocoapods
      
    - uses: release-drafter/release-drafter@v5
      if: ${{ github.event.inputs.action_tag == 'yes' }}
      with:
        name: v${{ github.event.inputs.tag }}
        tag: ${{ github.event.inputs.tag }}
        version: ${{ github.event.inputs.tag }}
        publish: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Pods - Stuff
      run: |
        set -eo pipefail
        export LIB_VERSION={{ github.event.inputs.tag }}
        pod lib lint ReleaseTestGJ.podspec --allow-warnings
        pod trunk push ReleaseTestGJ.podspec --allow-warnings --synchronous
        pod repo update
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}