name: Release

on:
  release:
    types: [ published ]

defaults:
  run:
    shell: bash -l {0}

jobs:
  Build:
      name: Build
      permissions:
        statuses: write
        pull-requests: write
      uses: ./.github/workflows/_build.yml
  Deploy:
    name: Release to Cocoapods
    runs-on: macos-11
    environment: Publishing
    needs: [Build]
    timeout-minutes: 30
    steps:
    - name: Check out source code
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Install cocoapods
      run: gem install cocoapods

    - name: Publish Pods - ReleaseTestGJ
      run: |
        set -eo pipefail
        pod lib lint ReleaseTestGJ.podspec --allow-warnings
        pod trunk push ReleaseTestGJ.podspec --allow-warnings --synchronous
        pod repo update
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        LIB_VERSION: ${{ github.event.release.tag_name }}

  Docs:
    name: Build Docs
    runs-on: macos-11
    environment: Publishing
    needs: [Deploy]
    steps:

    - name: Check out source code
      uses: actions/checkout@v3
      with:
        ref: main
      
    - name: Making docs
      uses: actions/hello-world-javascript-action@main
      with:
        who-to-greet: 'Docs'  
