name: Release

on: [workflow_dispatch]

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main

    - name: Get release tag
      id: get_release_tag
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Bump version
      run: |
        rake update_all_modules_version POD_VERSION=${{ steps.get_release_tag.outputs.tag_name }}

    - name: Commit version change
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
          commit_message: Version bump
          tagging_message: ${{ steps.get_release_tag.outputs.tag_name }}
          
    - name: Publish release
      uses: release-drafter/release-drafter@v5
      with:
        publish: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}