name: Release

on:
  release:
    types: [ published ]

defaults:
  run:
    shell: bash -l {0}

jobs:
  Release:
    name: Release to Cocoapods
    runs-on: macos-11
    environment: Publishing
    timeout-minutes: 30
    steps:
    - name: Check out source code
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Install cocoapods
      run: gem install cocoapods

    - name: Publish Pods - ReleaseTestGJ
      run: |
        set -eo pipefail
        pod lib lint ReleaseTestGJ.podspec --allow-warnings
        pod trunk push ReleaseTestGJ.podspec --allow-warnings --synchronous
        pod repo update
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        LIB_VERSION: ${{ github.event.release.tag_name }}